-- farming_mtg/init.lua

-- Aliases for Mintest Game farming mod
minetest.register_alias("farming:hoe_wood","base_hoes:wood")
minetest.register_alias("farming:hoe_stone","base_hoes:stone")
minetest.register_alias("farming:hoe_steel","base_hoes:steel")
minetest.register_alias("farming:hoe_bronze","base_hoes:bronze")
minetest.register_alias("farming:hoe_mese","base_hoes:mese")
minetest.register_alias("farming:hoe_diamond","base_hoes:diamond")

minetest.register_alias("farming:soil", "base_soil:dirt")
minetest.register_alias("farming:soil_wet", "base_soil:dirt_wet")
minetest.register_alias("farming:dry_soil", "base_soil:dry_dirt")
minetest.register_alias("farming:dry_soil_wet", "base_soil:dry_dirt_wet")
minetest.register_alias("farming:desert_sand_soil", "base_soil:desert_sand")
minetest.register_alias("farming:desert_sand_soil_wet", "base_soil:desert_sand_wet")

minetest.register_alias("farming:bread", "wheat:bread")
minetest.register_alias("farming:flour", "wheat:flour")
minetest.register_alias("farming:seed_wheat", "wheat:wheat_seed")
minetest.register_alias("farming:straw", "wheat:straw")
minetest.register_alias("farming:wheat", "wheat:wheat")
minetest.register_alias("farming:wheat_1", "wheat:wheat_1")
minetest.register_alias("farming:wheat_2", "wheat:wheat_2")
minetest.register_alias("farming:wheat_3", "wheat:wheat_3")
minetest.register_alias("farming:wheat_4", "wheat:wheat_4")
minetest.register_alias("farming:wheat_5", "wheat:wheat_5")
minetest.register_alias("farming:wheat_6", "wheat:wheat_6")
minetest.register_alias("farming:wheat_7", "wheat:wheat_7")
minetest.register_alias("farming:wheat_8", "wheat:wheat_8")

minetest.register_alias("farming:string","cotton:string")
minetest.register_alias("farming:cotton_wild", "cotton:wild")
minetest.register_alias("farming:seed_cotton", "cotton:cotton_seed")
minetest.register_alias("farming:cotton", "cotton:cotton")
minetest.register_alias("farming:cotton_1", "cotton:cotton_1")
minetest.register_alias("farming:cotton_2", "cotton:cotton_2")
minetest.register_alias("farming:cotton_3", "cotton:cotton_3")
minetest.register_alias("farming:cotton_4", "cotton:cotton_4")
minetest.register_alias("farming:cotton_5", "cotton:cotton_5")
minetest.register_alias("farming:cotton_6", "cotton:cotton_6")
minetest.register_alias("farming:cotton_7", "cotton:cotton_7")
minetest.register_alias("farming:cotton_8", "cotton:cotton_8")
