-- tools_mtg/init.lua

-- Aliases to support loading worlds using nodes following the old naming convention
-- These can also be helpful when using chat commands, for example /giveme
minetest.register_alias("WPick", "base_tools:wood_pick")
minetest.register_alias("STPick", "base_tools:stone_pick")
minetest.register_alias("SteelPick", "base_tools:steel_pick")
minetest.register_alias("MesePick", "base_tools:mese_pick")
minetest.register_alias("WShovel", "base_tools:wood_shovel")
minetest.register_alias("STShovel", "base_tools:stone_shovel")
minetest.register_alias("SteelShovel", "base_tools:steel_shovel")
minetest.register_alias("WAxe", "base_tools:wood_axe")
minetest.register_alias("STAxe", "base_tools:stone_axe")
minetest.register_alias("SteelAxe", "base_tools:steel_axe")
minetest.register_alias("WSword", "base_tools:wood_sword")
minetest.register_alias("STSword", "base_tools:stone_sword")
minetest.register_alias("SteelSword", "base_tools:steel_sword")


minetest.register_alias("default:pick_wood", "base_tools:wood_pick")
minetest.register_alias("default:pick_stone", "base_tools:stone_pick")
minetest.register_alias("default:pick_bronze", "base_tools:bronze_pick")
minetest.register_alias("default:pick_steel", "base_tools:steel_pick")
minetest.register_alias("default:pick_mese", "base_tools:mese_pick")
minetest.register_alias("default:pick_diamond", "base_tools:diamond_pick")
minetest.register_alias("default:shovel_wood", "base_tools:wood_shovel")
minetest.register_alias("default:shovel_stone", "base_tools:stone_shovel")
minetest.register_alias("default:shovel_bronze", "base_tools:bronze_shovel")
minetest.register_alias("default:shovel_steel", "base_tools:steel_shovel")
minetest.register_alias("default:shovel_mese", "base_tools:mese_shovel")
minetest.register_alias("default:shovel_diamond", "base_tools:diamond_shovel")
minetest.register_alias("default:axe_wood", "base_tools:wood_axe")
minetest.register_alias("default:axe_stone", "base_tools:stone_axe")
minetest.register_alias("default:axe_bronze", "base_tools:bronze_axe")
minetest.register_alias("default:axe_steel", "base_tools:steel_axe")
minetest.register_alias("default:axe_mese", "base_tools:mese_axe")
minetest.register_alias("default:axe_diamond", "base_tools:diamond_axe")
minetest.register_alias("default:sword_wood", "base_tools:wood_sword")
minetest.register_alias("default:sword_stone", "base_tools:stone_sword")
minetest.register_alias("default:sword_bronze", "base_tools:bronze_sword")
minetest.register_alias("default:sword_steel", "base_tools:steel_sword")
minetest.register_alias("default:sword_mese", "base_tools:mese_sword")
minetest.register_alias("default:sword_diamond", "base_tools:diamond_sword")

